# Generated by Django 5.1.2 on 2024-10-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Amount', models.IntegerField()),
                ('Income', models.IntegerField()),
                ('Accountnumber', models.IntegerField()),
                ('Securitypin', models.IntegerField()),
                ('Interest', models.IntegerField()),
                ('Collateral', models.CharField(max_length=30)),
            ],
        ),
    ]
